name: Daily HF Papers

on:
  schedule:
    # 매일 00:15 UTC = 09:15 KST
    - cron: "15 0 * * *"
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: seen-${{ github.ref }}
  cancel-in-progress: false

env:
  N: "10"
  OPENAI_MODEL: gpt-4.1-mini
  PDF_MAX_CHARS: 120000
#fv
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npx prettier . --check

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Generate daily post
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EXCLUDE_UPLOADED: "1"
          SEEN_DB: "_scripts/seen_papers.txt"
        run: python scripts/build_daily_post.py

      - name: Commit & push seen db
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ._scripts/seen_papers.txt
          git commit -m "chore(state): update seen db" || exit 0
          git pull --rebase
          git push origin HEAD:${{ github.ref_name }}

      # GitHub Pages 워크플로는 GITHUB_TOKEN 커밋에 의해 자동 트리거되지 않음.
      # 같은 잡에서 Pages 빌드·배포를 수행한다.

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Build Jekyll
        uses: actions/jekyll-build@v4
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
