name: Daily HF Papers

on:
  schedule:
    - cron: "15 0 * * *" # 09:15 KST
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: seen-${{ github.ref_name }}
  cancel-in-progress: false

env:
  N: "10"
  OPENAI_MODEL: gpt-4.1-mini
  PDF_MAX_CHARS: 40000
  OPENAI_RPM_LIMIT: "3"
  MAX_OUT_TOKENS: "300"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # token: ${{ secrets.GH_PAT }}   # org가 read-only면 주석 해제

      # Optional: 포맷 체크. 실패해도 배포 계속
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: "npm" }
      - run: npm ci
      - name: Prettier check (non-blocking)
        run: npx prettier . --check || echo "prettier failed"

      # Daily post 생성
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Generate daily post
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EXCLUDE_UPLOADED: "1"
          SEEN_DB: "_scripts/seen_papers.txt"
        run: python _scripts/post.py

      # 생성물 커밋
      - name: Commit & push generated posts and seen db
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _posts/*.md _scripts/seen_papers.txt || true
          git commit -m "chore(posts): add daily post" || true
          git pull --rebase
          git push origin HEAD:${{ github.ref_name }}

      # # 커스텀 Jekyll 4 빌드
      # - name: Setup Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: "3.2"
      #     bundler-cache: true

      # - name: Install gems
      #   run: bundle install --jobs 4 --retry 3

      # - name: Build site with Jekyll
      #   env:
      #     JEKYLL_ENV: production
      #   run: bundle exec jekyll build --trace -d _site

      # - name: Configure Pages
      #   uses: actions/configure-pages@v5

      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v4
      #   with:
      #     path: _site

      # - name: Deploy to GitHub Pages
      #   uses: actions/deploy-pages@v4
