name: Daily HF Papers

on:
  schedule:
    - cron: "15 0 * * *"
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: seen-${{ github.ref_name }}
  cancel-in-progress: false

env:
  N: "10"
  OPENAI_MODEL: gpt-4.1-mini
  PDF_MAX_CHARS: 120000

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # token: ${{ secrets.GH_PAT }}   # org가 read-only면 주석 해제

      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: "npm" }
      - run: npm ci
      - run: npx prettier . --check

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt

      - name: Generate daily post
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EXCLUDE_UPLOADED: "1"
          SEEN_DB: "_scripts/seen_papers.txt"
        run: python _scripts/build_daily_post.py

      - name: Commit & push generated posts and seen db
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _posts/*.md _scripts/seen_papers.txt
          git commit -m "chore(posts): add daily post [skip ci]" || exit 0
          git pull --rebase
          git push origin HEAD:${{ github.ref_name }}

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Build Jekyll
        uses: actions/jekyll-build@v4
        with:
          source: ./
          destination: ./_site

      # - name: Link check _site
      #   uses: lycheeverse/lychee-action@v1
      #   with:
      #     args: >-
      #       --no-progress --verbose
      #       --accept 200,206,403,429
      #       --max-retries 3 --retry-wait-time 2
      #       --exclude-file .lycheeignore
      #       --scheme https,http
      #       "_site/**/*.html"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
